### PR TITLE
Donovan oauth2 authentication

### PR DESCRIPTION
**Pull request by UhOhDonovan**
Authenticate users and maintain a login session using OAuth2 specifications

### CODE REVIEW

**Comment by UhOhDonovan** [comment]
Currently using fake cryptographic data

**Review by Evan-Pozzo — APPROVED** [review]
Looks good

**Comment by adam-burton-stl** [comment]
Good

**Comment by adam-burton-stl** [comment]
good

**Review by adam-burton-stl — APPROVED** [review]
I figured it out, yippee!

**Pull request merged**
